apiVersion: v1
kind: ConfigMap
metadata:
  name: oban-config
  namespace: oban-eats
data:
  ENVIRONMENT: "PROD"
  API_TITLE: "Oban Eats API - Production"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "oban_eats"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
